// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

/**
 @file
 @internalComponent - Internal Symbian test code 
*/

#ifndef __TVWUIDS_H__
#define __TVWUIDS_H__

#include <w32std.h>

#include "tvwuids.HRH"

//
// Application Uids
//

const TUid KUidViewAppOne={KUidViewAppOneValue};
const TUid KUidViewAppTwo={KUidViewAppTwoValue};
const TUid KUidViewAppThree={KUidViewAppThreeValue};

//
// View Uids
//

const TUid KUidViewOne={KUidViewOneValue};
const TUid KUidViewTwo={KUidViewTwoValue};

//
// Message Uids
//

const TUid KUidTestCustomMesssageId={0x34343434};
const TUid KUidStartScheduler={0x45454545};
const TUid KUidActivationOOM={0x56565656};
const TUid KUidActivationPanic={0x67676767};
const TUid KUidSlowActivation={0x78787878};
const TUid KUidEndurance={0x89898989};
const TUid KUidSluggishActivation={0x90909090};
const TUid KUidSluggishDeactivation={0x43434343};
const TUid KUidActivationExit={0x54545454};
const TUid KUidActivateAgain={0x65656565};


#endif
