/*
* Copyright (c) 1998-1999 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/


#ifndef __LAFBTGPC_H__
#define __LAFBTGPC_H__

#include <lafpublc.h>

/**
 * @internal
 * Do not use
 */
class LafButtonGroupContainer
    {
public:
	IMPORT_C static TInt ButtonType(TInt aUse);
	IMPORT_C static TInt Location(TInt aUse);
	};	

#endif //__LAFBTGPC_H__
