/*
* Copyright (c) 1997-1999 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/


#ifndef __LAFSTD_H__
#define __LAFSTD_H__

#include "lafpanic.h"

#include <e32std.h>
#include <gulcolor.h>

GLREF_C void Panic(TLafPanic aPanic);


#endif //__LAFSTD_H__
