// Copyright (c) 1997-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

#include <e32std.h>
#include "GULSTD.H"


IMPORT_C void ColorUtils_Stub1();
EXPORT_C void ColorUtils_Stub1()
	{
	Panic(EEgulPanicImplementationMoved);
	}

IMPORT_C void ColorUtils_Stub2();
EXPORT_C void ColorUtils_Stub2()
	{
	Panic(EEgulPanicImplementationMoved);
	}

IMPORT_C void ColorUtils_Stub3();
EXPORT_C void ColorUtils_Stub3()
	{
	Panic(EEgulPanicImplementationMoved);
	}

