/*
* ==============================================================================
*  Name        : CommonDialogsMbm.mmp
*  Part of     : Common File Dialogs / CommonDialogs.dll
*  Description : This is project specification file for CommonDialogs bitmaps
*                file.
*  Version     : ?Version
*
*  Copyright (c) 2002-2006 Nokia Corporation.
*  This material, including documentation and any related 
*  computer programs, is protected by copyright controlled by 
*  Nokia Corporation. All rights are reserved. Copying, 
*  including reproducing, storing, adapting or translating, any 
*  or all of this material requires the prior written consent of 
*  Nokia Corporation. This material also contains confidential 
*  information which may not be disclosed to others without the 
*  prior written consent of Nokia Corporation.
* ==============================================================================
*/

START BITMAP CommonDialogs.mbm

// target path
TARGETPATH APP_BITMAP_DIR

// bitmap header
HEADER

// source path to bitmaps2


// mbm file context

//
// Icons for different file types
//

// Image file
SOURCE c8   qgn_prop_fmgr_file_image.bmp
SOURCE 1    qgn_prop_fmgr_file_image_mask.bmp

// gms picture 
SOURCE c8   qgn_prop_fmgr_file_gms.bmp
SOURCE 1    qgn_prop_fmgr_file_gms_mask.bmp

// precense logo
SOURCE c8   qgn_prop_fmgr_dyc_logos.bmp
SOURCE 1    qgn_prop_fmgr_dyc_logos_mask.bmp

// link file
SOURCE c8   qgn_prop_fmgr_file_link.bmp
SOURCE 1    qgn_prop_fmgr_file_link_mask.bmp

// digital type of files (eg. voice recorder)
SOURCE c8   qgn_prop_fmgr_file_voicerec.bmp
SOURCE 1    qgn_prop_fmgr_file_voicerec_mask.bmp

// sound file
SOURCE c8   qgn_prop_fmgr_file_sound.bmp
SOURCE 1    qgn_prop_fmgr_file_sound_mask.bmp

// playlist file
SOURCE c8   qgn_prop_fmgr_file_playlist.bmp
SOURCE 1    qgn_prop_fmgr_file_playlist_mask.bmp

// sample type of files (eg. composer)
SOURCE c8   qgn_prop_fmgr_file_compo.bmp
SOURCE 1    qgn_prop_fmgr_file_compo_mask.bmp

// apps file
SOURCE c8   qgn_prop_fmgr_file_apps.bmp
SOURCE 1    qgn_prop_fmgr_file_apps_mask.bmp

// video file
SOURCE c8   qgn_prop_fmgr_file_video.bmp
SOURCE 1    qgn_prop_fmgr_file_video_mask.bmp

// game file 
SOURCE c8   qgn_prop_fmgr_file_game.bmp 
SOURCE 1	qgn_prop_fmgr_file_game_mask.bmp

// other file
SOURCE c8   qgn_prop_fmgr_file_other.bmp
SOURCE 1    qgn_prop_fmgr_file_other_mask.bmp


// End of mbm File
END

// End of File

