/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/

// This header file contains the customisation implementation identity for Avkon2MifHeader_inst
// It was generated by:
// MifToCdlIndex -p..\Avkon2MifHeader \epoc32\data\z\resource\apps\avkon2.mif Avkon2MifHeader 0x102827CF
// This file may be manually modified.

#ifndef AVKON2MIFHEADER_INST_H
#define AVKON2MIFHEADER_INST_H
#include "mifheader.cdl.custom.h"
#include "avkon2mifheader_inst.hrh"

namespace Avkon2MifHeader_inst
{

const TInt KCdlInstanceId = _CDL_Avkon2MifHeader_inst_KCdlInstanceId;
using MifHeader::KCdlInterface;
using MifHeader::KCdlInterfaceUidValue;
GLREF_D const MifHeader::SCdlImpl KCdlImpl;

} // end of namespace Avkon2MifHeader_inst
#endif // AVKON2MIFHEADER_INST_H
