// Copyright (c) 1997-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

#ifndef __COEVER_H__
#define __COEVER_H__

/**
@internalComponent
*/
const TInt KCoeMajorVersionNumber=5;

/**
@internalComponent
*/
const TInt KCoeMinorVersionNumber=0;

/**
@internalComponent
*/
const TInt KCoeBuildVersionNumber=256;

#endif	// __COEVER_H__
