//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//
PRINT Run TCapability2 UiktestServer Test
//
PRINT INFO: Set test server capability to WriteDeviceData (00000020)
RUN_PROGRAM -1 setcap UiktestServer.exe 00000020 UiktestServer0020.exe
PRINT INFO: Test Server capability now set to WriteDeviceData (00000020)
//
LOAD_SUITE UiktestServer0020
RUN_TEST_STEP 100 UiktestServer0020 TCapability2
